title: Raj Singh Bagri 
logo: "/photo.png?raw=true" 
description: > 
 Startups| IIT Bombay Batch 2022
  <br>
  <br>
  <a href="https://topmate.io/raj_bagri" title="I am not in Linkedin by choice😅"><img src="https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png" width="60" height='60' alt="LinkedIn logo " /></a>
  <a href="https://www.instagram.com/rajsingh__bagri/" title = "Connect with Raj on instagram"><img src="https://www.freepnglogos.com/uploads/logo-ig-png/logo-ig-instagram-new-logo-vector-download-13.png" width="60" height="60" alt="Insta logo" /></a>
   <a href="https://www.facebook.com/profile.php?id=100078129545969" title = "Connect with Raj on FB"><img src="https://www.freeiconspng.com/uploads/logo-facebook-png-transparent-image-28.png" width="60" height='60' alt="FB logo " /></a>
  
  <a href="mailto:rajsinghbagri18@gmail.com" title="Send an Email to Raj"><img src="https://logodownload.org/wp-content/uploads/2018/03/gmail-logo-4-1.png" width="55" height='55' alt="Gmail logo" /></a>
  
  
 
 
 
  

theme: jekyll-theme-minimal
  
