title: Raj Singh Bagri 
logo: "/photo.png?raw=true" 
description: > 
 Product Consultant|Freelancer
  <br>
  <br>
  <a href="https://www.linkedin.com/in/raj-singh-bagri-9140b7171/" title=" Connect to Raj on LinkedIn"><img src="https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png" width="60" height='60' alt="LinkedIn logo " /></a>
  <a href="https://www.instagram.com/rajsingh__bagri/" title = "Connect to Raj in instagram"><img src="https://www.freepnglogos.com/uploads/logo-ig-png/logo-ig-instagram-new-logo-vector-download-13.png" width="60" height="60" alt="Skype logo" /></a>
  
  <a href="mailto:rajsinghbagri18@gmail.com" title="Send an Email to Raj"><img src="https://logodownload.org/wp-content/uploads/2018/03/gmail-logo-4-1.png" width="60" height='60' alt="Gmail logo" /></a>
  
  
  <a href="https://twitter.com/raj_singh_bagri" title = "Follow Raj on Twitter"><img src="https://www.freepnglogos.com/uploads/twitter-logo-png/twitter-logo-vector-png-clipart-1.png" width="60" height='60' alt="Gmail logo " /></a>
  
 
 
  

theme: jekyll-theme-minimal
  
