title: Raj Singh Bagri 
logo: "/photo.png?raw=true" 
description: > 
 Product Consultant|Freelancer
  <br><br>
  <a href="mailto:rajsinghbagri18@gmail.com">rajsinghbagri18@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/raj-singh-bagri-9140b7171/">LinkedIn Profile</a>  
theme: jekyll-theme-minimal
