title: Raj Singh Bagri 
logo: "/photo.png?raw=true" 
description: > 
 Product Consultant|Freelancer
  <br>
  <br>
  <a href="https://www.linkedin.com/in/raj-singh-bagri-9140b7171/" title="LinkedIn"><img src="https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png" width="auto" height='40' alt="LinkedIn logo " /></a>
  <br>
  <a href="mailto:rajsinghbagri18@gmail.com"><img src="https://logodownload.org/wp-content/uploads/2018/03/gmail-logo-4-1.png" width="auto" height='40' alt="Gmail logo " /></a> </a>
  <br>
  
  <a href="https://twitter.com/raj_singh_bagri"> Profile</a>
  
theme: jekyll-theme-minimal

